
/**
 * Utility to clean up malformed HTML generated by AI models.
 * Fixes broken tags, mismatched headers, and stray artifacts.
 */
export const cleanHTML = (html: string): string => {
  if (!html) return '';

  let cleaned = html;

  // 1. Fix malformed heading tags (e.g., <h>, </h>, <h2)
  cleaned = cleaned.replace(/<h\d?>/gi, '<h3>');
  cleaned = cleaned.replace(/<\/h\d?>/gi, '</h3>');
  cleaned = cleaned.replace(/<h\s*>/gi, '<h3>');
  cleaned = cleaned.replace(/<\/h\s*>/gi, '</h3>');

  // 2. Fix malformed bold tags
  cleaned = cleaned.replace(/<b\s*\/?>/gi, '<b>');
  cleaned = cleaned.replace(/<\/b\s*>/gi, '</b>');
  cleaned = cleaned.replace(/<strong\s*\/?>/gi, '<b>');
  cleaned = cleaned.replace(/<\/strong\s*>/gi, '</b>');
  cleaned = cleaned.replace(/<b\s+[^>]*>/gi, '<b>');

  // 3. Fix malformed italic tags
  cleaned = cleaned.replace(/<i\s*\/?>/gi, '<i>');
  cleaned = cleaned.replace(/<\/i\s*>/gi, '</i>');
  cleaned = cleaned.replace(/<em\s*\/?>/gi, '<i>');
  cleaned = cleaned.replace(/<\/em\s*>/gi, '</i>');
  cleaned = cleaned.replace(/<i\s+[^>]*>/gi, '<i>');

  // 4. Fix malformed paragraph tags
  cleaned = cleaned.replace(/<p\s*>/gi, '<p>');
  cleaned = cleaned.replace(/<\/p\s*>/gi, '</p>');

  // 5. Remove stray brackets that often appear in LLM outputs (e.g. [Chapter 1], [Section])
  // Only remove them if they are at the start/end of lines or wrapping headers
  cleaned = cleaned.replace(/^\[|\]$/gm, '');
  
  // 6. Fix common mismatched tags (e.g. <b>text</i>)
  // This is harder with regex, but we can do basic balancing for the most common ones
  const tags = ['p', 'b', 'i', 'h3'];
  tags.forEach(tag => {
    const openCount = (cleaned.match(new RegExp(`<${tag}>`, 'g')) || []).length;
    const closeCount = (cleaned.match(new RegExp(`</${tag}>`, 'g')) || []).length;
    
    if (openCount > closeCount) {
      cleaned += `</${tag}>`.repeat(openCount - closeCount);
    }
  });

  // 7. Ensure all text is inside a block-level element (p or h3)
  // We split by tags and wrap any non-tag text that isn't already inside p or h3
  // A simpler way for LLM output is to ensure it doesn't end with hanging text
  if (cleaned.length > 0 && !cleaned.trim().endsWith('>')) {
    // If it ends with text, find the last opening tag
    const lastOpenP = cleaned.lastIndexOf('<p>');
    const lastCloseP = cleaned.lastIndexOf('</p>');
    if (lastOpenP > lastCloseP) {
      cleaned += '</p>';
    } else {
      // If no open p, it's just hanging text at the end
      // This is handled by the balancing above usually, but let's be safe
    }
  }

  // 8. Remove any weird artifacts like "```html" or "```" or stray brackets
  cleaned = cleaned.replace(/```html/gi, '');
  cleaned = cleaned.replace(/```/g, '');
  cleaned = cleaned.replace(/【|】/g, ''); // Common AI artifacts
  cleaned = cleaned.replace(/\[\s*Chapter\s*\d+\s*\]/gi, ''); // Remove [Chapter X] style artifacts

  return cleaned;
};
