/**
 * Cleans HTML generated by AI for use in TipTap WordEditor.
 *
 * Two layers, in order:
 * 1. DOMPurify — real HTML parser, removes XSS vectors that regex-based
 *    sanitizers miss (mutation XSS, attribute encoding tricks, nested
 *    svg/math, slash-separated attrs, JAVA\tSCRIPT: schemes, etc.)
 * 2. AI-output normalization — strip markdown artifacts, convert <strong>
 *    to <b>, balance unclosed tags, etc. Pure presentation munging.
 */

import DOMPurify from 'isomorphic-dompurify';

// What we accept in the editor body. The AI is instructed to produce only
// <p> and <b>; <h1>/<h2>/<h3> are added by the app for chapter/section
// headings; <div> is needed for the page-break separator.
const ALLOWED_TAGS = ['p', 'b', 'i', 'u', 'br', 'ul', 'ol', 'li', 'h1', 'h2', 'h3', 'div'];

// We don't render any URLs in chapter content, so href/src are not in the
// attribute allow-list. The only attribute we need is `class` (for the
// page-break div) and `data-page-break` (DOMPurify needs data attrs allowed).
const ALLOWED_ATTR = ['class', 'data-page-break'];

const sanitize = (html: string): string =>
  DOMPurify.sanitize(html, {
    ALLOWED_TAGS,
    ALLOWED_ATTR,
    ALLOW_DATA_ATTR: true,
    // No need for URL allow-list — neither href nor src is in ALLOWED_ATTR,
    // so any URL-bearing attribute is stripped before this matters.
  });

export const cleanHTML = (html: string): string => {
  if (!html) return '';
  let c = html;

  // 0. Security: parse + sanitize with DOMPurify. Everything below this
  //    line is presentation cleanup running against already-safe HTML.
  c = sanitize(c);

  // 1. Strip any heading tags the AI produces despite being told not to.
  //    Replace <h1>…</h1>, <h2>…</h2>, <h3>…</h3> with <b>…</b> so the
  //    text is preserved but rendered as inline bold, not a heading.
  c = c.replace(/<h[1-6][^>]*>(.*?)<\/h[1-6]>/gis, '<b>$1</b>');

  // 2. Normalise bold/italic — DOMPurify keeps <strong>/<em> if allowed,
  //    but our editor schema uses <b>/<i>. Convert before TipTap sees it.
  c = c.replace(/<strong[^>]*>/gi, '<b>');
  c = c.replace(/<\/strong>/gi, '</b>');
  c = c.replace(/<em[^>]*>/gi, '<i>');
  c = c.replace(/<\/em>/gi, '</i>');

  // 3. Strip attributes from <p> tags (DOMPurify removed dangerous ones,
  //    but we also don't want any styling/classes on body paragraphs).
  c = c.replace(/<p\s+[^>]*>/gi, '<p>');
  c = c.replace(/<\/p\s*>/gi, '</p>');

  // 4. Remove legacy page-break style paragraphs from older content
  c = c.replace(/<p[^>]*style="[^"]*page-break[^"]*"[^>]*>.*?<\/p>/gis, '');

  // 5. Remove AI markdown artifacts
  c = c.replace(/```html\s*/gi, '');
  c = c.replace(/```\s*/g, '');
  c = c.replace(/【[^】]*】/g, '');
  c = c.replace(/\[Chapter\s*\d+\]/gi, '');
  c = c.replace(/\[Section[^\]]*\]/gi, '');

  // 6. Remove stray bracket wrappers on their own lines
  c = c.replace(/^\[|\]$/gm, '');

  // 7. Balance unclosed <p>, <b>, <i> tags. DOMPurify usually closes for
  //    us, but mid-stream chunks can arrive with an open tag at the tail.
  ['p', 'b', 'i'].forEach(tag => {
    const opens = (c.match(new RegExp(`<${tag}>`, 'g')) || []).length;
    const closes = (c.match(new RegExp(`</${tag}>`, 'g')) || []).length;
    if (opens > closes) c += `</${tag}>`.repeat(opens - closes);
  });

  // 8. Strip completely empty paragraphs at the start (prevents blank first line)
  c = c.replace(/^(<p>\s*<\/p>)+/, '');

  return c.trim();
};

/**
 * Sanitize a FULL stored document (chapter HTML) without destroying its
 * structure. Unlike cleanHTML — which is for AI body fragments where
 * headings are forbidden — this preserves the app's own <h1>/<h2>/<h3>
 * headings and page-break divs. Use on the Firestore load path and anywhere
 * a whole chapter (not a fragment) passes through sanitization.
 */
export const cleanDocumentHTML = (html: string): string => {
  if (!html) return '';
  let c = sanitize(html);

  // Normalise bold/italic to the editor's schema
  c = c.replace(/<strong[^>]*>/gi, '<b>');
  c = c.replace(/<\/strong>/gi, '</b>');
  c = c.replace(/<em[^>]*>/gi, '<i>');
  c = c.replace(/<\/em>/gi, '</i>');

  // Balance unclosed tags (defensive — stored content should be balanced)
  ['p', 'b', 'i'].forEach(tag => {
    const opens = (c.match(new RegExp(`<${tag}>`, 'g')) || []).length;
    const closes = (c.match(new RegExp(`</${tag}>`, 'g')) || []).length;
    if (opens > closes) c += `</${tag}>`.repeat(opens - closes);
  });

  return c.trim();
};
