/**
 * Cleans HTML generated by AI for use in TipTap WordEditor.
 *
 * Philosophy:
 * - The AI is instructed to output ONLY <p> and <b> tags (no headings).
 * - The frontend adds <h1> (chapter title) and <h2> (section title) itself.
 * - This cleaner strips any headings the AI sneaks in anyway, fixes
 *   malformed tags, removes common AI artifacts, and prevents XSS.
 */

// Allowed tags — everything else is stripped
const ALLOWED_TAGS = new Set(['p', 'b', 'i', 'u', 'br', 'ul', 'ol', 'li', 'h1', 'h2', 'h3', 'div', 'span']);

/**
 * Strip all HTML event-handler attributes (onclick, onerror, onload, etc.)
 * and dangerous attributes (style with expression(), javascript: URLs).
 * This is the primary XSS prevention layer.
 */
const stripDangerousAttributes = (html: string): string => {
  // Remove all on* event handler attributes
  let c = html.replace(/\s+on\w+\s*=\s*(?:"[^"]*"|'[^']*'|[^\s>]*)/gi, '');
  // Remove javascript: in href/src attributes
  c = c.replace(/(href|src)\s*=\s*["']?\s*javascript:/gi, '$1="');
  // Remove data: URLs in src (potential XSS vector)
  c = c.replace(/src\s*=\s*["']?\s*data:/gi, 'src="');
  return c;
};

/**
 * Remove disallowed HTML tags while keeping their text content.
 * Two-pass approach:
 *   1. Completely remove dangerous tags AND their content (script, iframe, etc.)
 *   2. Strip any remaining tag not in ALLOWED_TAGS (keeps inner text)
 */
const stripDisallowedTags = (html: string): string => {
  // Pass 1: Completely remove these tags AND their content (no text kept)
  let c = html.replace(/<(script|iframe|object|embed|form|link|meta|base|style)[^>]*>[\s\S]*?<\/\1>/gi, '');
  c = c.replace(/<(script|iframe|object|embed|form|link|meta|base|style)[^>]*\/?>/gi, '');
  // Remove <img> tags with any event handler (onerror, onload, etc.)
  c = c.replace(/<img[^>]*\bon\w+[^>]*>/gi, '');

  // Pass 2: Strip any tag NOT in the ALLOWED_TAGS whitelist (keeps inner text)
  // Matches opening tags like <svg ...>, closing tags like </svg>, and self-closing <svg ... />
  c = c.replace(/<\/?([a-zA-Z][a-zA-Z0-9]*)\b[^>]*\/?>/gi, (match, tagName) => {
    return ALLOWED_TAGS.has(tagName.toLowerCase()) ? match : '';
  });

  return c;
};

export const cleanHTML = (html: string): string => {
  if (!html) return '';
  let c = html;

  // 0. XSS prevention — strip dangerous elements and attributes first
  c = stripDisallowedTags(c);
  c = stripDangerousAttributes(c);

  // 1. Strip any heading tags the AI produces despite being told not to.
  //    Replace <h1>…</h1>, <h2>…</h2>, <h3>…</h3> with <b>…</b>
  //    so the text is preserved but rendered as inline bold, not a heading.
  c = c.replace(/<h[1-6][^>]*>(.*?)<\/h[1-6]>/gis, '<b>$1</b>');

  // 2. Normalise bold
  c = c.replace(/<strong[^>]*>/gi, '<b>');
  c = c.replace(/<\/strong>/gi, '</b>');

  // 3. Normalise italic
  c = c.replace(/<em[^>]*>/gi, '<i>');
  c = c.replace(/<\/em>/gi, '</i>');

  // 4. Clean up malformed paragraph tags — strip all attributes from <p> tags
  c = c.replace(/<p\s+[^>]*>/gi, '<p>');
  c = c.replace(/<\/p\s*>/gi, '</p>');

  // 5. Remove page-break style paragraphs the old system generated
  c = c.replace(/<p[^>]*style="[^"]*page-break[^"]*"[^>]*>.*?<\/p>/gis, '');

  // 6. Remove AI markdown artifacts
  c = c.replace(/```html\s*/gi, '');
  c = c.replace(/```\s*/g, '');
  c = c.replace(/【[^】]*】/g, '');
  c = c.replace(/\[Chapter\s*\d+\]/gi, '');
  c = c.replace(/\[Section[^\]]*\]/gi, '');

  // 7. Remove stray bracket wrappers on their own lines
  c = c.replace(/^\[|\]$/gm, '');

  // 8. Balance unclosed <p> and <b> tags
  ['p', 'b', 'i'].forEach(tag => {
    const opens = (c.match(new RegExp(`<${tag}>`, 'g')) || []).length;
    const closes = (c.match(new RegExp(`</${tag}>`, 'g')) || []).length;
    if (opens > closes) c += `</${tag}>`.repeat(opens - closes);
  });

  // 9. Strip completely empty paragraphs at the start (prevents blank first line)
  c = c.replace(/^(<p>\s*<\/p>)+/, '');

  return c.trim();
};